- hosts: geth_node
  tasks:
    - name: Stop geth
      systemd:
        state: stopped
        name: geth.service
    - name: Delete db
      command: geth removedb
      become: "{{ geth_user }}"
    - name: "Remove {{ datadir }}"
      file:
        name: "{{ datadir }}"
        state: absent
