---
- name: Set hostname
  hostname:
    name: "{{ nodename }}"

- name: Perform apt dist upgrade
  apt:
    autoremove: yes
    update_cache: yes
    upgrade: dist
    dpkg_options: "Acquire::Check-Valid-Until=false,update"

- name: Add packages
  apt:
    pkg: "{{ item }}"
  with_items: "{{ apt_packages }}"
