- name: Create nonce for genesis block
  command: openssl rand -hex 8
  register: nonce

- name: Copy genesis block template
  template:
    src: genesis.json
    dest: /etc/genesis.json
    owner: geth
    mode: 0644

- block:
  - name: Check if account password file has been created
    stat:
      path: ~/account.key
    register: account_password

  - name: Create password
    shell: openssl rand -hex 64 > ~/account.key
    when: account_password.stat.exists == False

  - name: Check if key store has been created
    stat:
      path: ~/.ethereum/geth/keystore
    register: keystore

  - name: Create new geth account
    command: geth account new --password ~/account.key
    when: keystore.stat.exists == False

  - name: Check if database has been created
    stat:
      path: ~/.ethereum/geth/chaindata
    register: chaindata

  - name: Initialize geth database
    command: geth init /etc/genesis.json
    when: chaindata.stat.exists == False

  become: true
  become_user: geth

- name: Load geth
  systemd:
    state: restarted
    daemon_reload: yes
    name: geth.service
    enabled: yes
