- name: Add geth group
  group:
    name: "{{ geth_group }}"

- name: Add geth user
  user:
    name: "{{ geth_user }}"
    group: "{{ geth_group }}"

- name: Download geth ({{ geth_version }})
  unarchive:
    src: "{{ geth_url }}"
    dest: /tmp/
    remote_src: yes
    creates: /tmp/{{ geth_version }}/geth

- name: Copy geth to /usr/local/bin
  copy:
    src: /tmp/{{ geth_version }}/geth
    dest: "{{ geth_path }}"
    remote_src: yes
    mode: 0777

- name: Create geth service file
  template:
    src: geth.service
    dest: /etc/systemd/system/geth.service
    mode: 0644

- name: Copy genesis block template
  template:
    src: genesis.json
    dest: /etc/genesis.json
    owner: geth
    mode: 0644

- block:
  - name: Create password
    shell: openssl rand -hex 64 > {{ geth_home }}/account.key
    args:
      creates: "{{ geth_home }}/account.key"

  - name: Create new geth account
    command: geth account new --password {{ geth_home }}/account.key
    args:
      creates: "{{ datadir }}/keystore"

  - name: Initialize geth database
    command: geth init /etc/genesis.json
    args:
      creates: "{{ datadir }}/geth/chaindata/CURRENT"

  become: true
  become_user: "{{ geth_user }}"

- name: Create static node file
  template:
    src: static-nodes.json
    dest: "{{ datadir }}/geth/static-nodes.json"
  when: use_bootnode is defined

- name: Load geth
  systemd:
    state: restarted
    daemon_reload: yes
    name: geth.service
    enabled: yes
